version: '3.8'

services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: calculator_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      # Automatically initializes database & tables on first startup
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - calc-net

  backend:
    build: ./backend
    image: hari930531/calculator-backend:latest
    container_name: calc-backend
    restart: always
    environment:
      DB_HOST: mysql-container
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: calculator_db
    ports:
      - "5000:5000"
    depends_on:
      mysql-container:
        condition: service_healthy
    networks:
      - calc-net

  frontend:
    image: nginx:alpine
    container_name: calc-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - calc-net

volumes:
  mysql-data:

networks:
  calc-net:
    driver: bridge